name: KlypApp
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.edihasaj.klyp
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    SWIFT_VERSION: "6.0"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: Klyp
    INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
    INFOPLIST_KEY_LSUIElement: YES
    INFOPLIST_KEY_NSHumanReadableCopyright: Copyright © Edi Hasaj
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    MARKETING_VERSION: "0.1.7"
    CURRENT_PROJECT_VERSION: "8"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    SWIFT_STRICT_CONCURRENCY: complete
targets:
  Klyp:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Klyp
    settings:
      base:
        PRODUCT_NAME: Klyp
  KlypTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: KlypTests
    dependencies:
      - target: Klyp
    settings:
      base:
        PRODUCT_NAME: KlypTests
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/Klyp.app/Contents/MacOS/Klyp
schemes:
  Klyp:
    build:
      targets:
        Klyp: all
        KlypTests: [test]
    test:
      targets:
        - KlypTests
